// DEVELOPMENT KEYS
require('dotenv').config()
module.exports = {
  SERVER_HOST:
    process.env.DEV_HOST,

  CLIENT_HOST:
    process.env.DEV_CLIENT_HOST,

  MONGODB_URI:
    process.env.DEV_MONGODB_URI,

  MONGO_CLIENT_SECRET:
    process.env.DEV_MONGODB_URI,

  SECRET_KEY:
    process.env.SECRET_KEY,

  GOOGLE_CLIENT_ID:
    process.env.GOOGLE_CLIENT_ID,

  GOOGLE_CALLBACK_URL:
    process.env.GOOGLE_CALLBACK_URL,

  GOOGLE_CLIENT_SECRET:
    process.env.GOOGLE_CLIENT_SECRET,

  TWILIO_ACCOUNT_SID:
    process.env.TWILIO_ACCOUNT_SID,

  TWILIO_PHONE_NUMBER:
    process.env.TWILIO_PHONE_NUMBER,

  TWILIO_AUTH_TOKEN:
    process.env.TWILIO_AUTH_TOKEN,

  CLOUDINARY_CLOUD_NAME:
    process.env.CLOUDINARY_CLOUD_NAME,

  CLOUDINARY_API_KEY:
    process.env.CLOUDINARY_API_KEY,

  CLOUDINARY_API_SECRET:
    process.env.CLOUDINARY_API_SECRET,
}

